/**
 * withWatchConnectivity — Expo config plugin
 *
 * Wires up WatchConnectivity on the iOS side so the Kanji-Learn iPhone app
 * can push Supabase JWT tokens and settings to the Apple Watch.
 *
 * What this plugin does on `expo prebuild`:
 *   1. Writes WatchConnectivityModule.swift into ios/KanjiLearn/
 *   2. Adds the Swift file to the Xcode project target
 *   3. Patches AppDelegate.swift to activate WCSession at launch
 *      (only when watchEnabled is set in user profile)
 *   4. Adds WatchConnectivity.framework to the Xcode target's linked frameworks
 *
 * The JavaScript side (auth.store.ts) calls the native module's
 * `pushTokensToWatch()` method whenever Supabase auth state changes
 * and the user has watchEnabled = true.
 */

const { withDangerousMod, withXcodeProject } = require('expo/config-plugins')
const fs = require('fs')
const path = require('path')

// ─── Swift source that will be written into ios/KanjiLearn/ ──────────────────

const WATCH_MODULE_SWIFT = `// WatchConnectivityModule.swift
// Auto-generated by plugins/withWatchConnectivity — do not edit manually.
// Called from auth.store.ts via NativeModules.WatchConnectivity.pushTokensToWatch()

import Foundation
import WatchConnectivity
import React

@objc(WatchConnectivity)
class WatchConnectivityModule: NSObject, WCSessionDelegate {

  private var session: WCSession?
  private static let shared = WatchConnectivityModule()

  override init() {
    super.init()
    if WCSession.isSupported() {
      let s = WCSession.default
      s.delegate = self
      s.activate()
      session = s
    }
  }

  // ── React Native bridge registration ────────────────────────────────────────

  @objc static func requiresMainQueueSetup() -> Bool { false }

  // Push tokens + settings to Watch via applicationContext.
  // applicationContext is delivered even when Watch is unreachable;
  // the Watch receives it as soon as it wakes.
  @objc func pushTokensToWatch(
    _ accessToken: String,
    refreshToken: String,
    expiresAt: Double,
    supabaseURL: String,
    apiBaseURL: String,
    dailyGoal: Int,
    reminderHour: Int,
    restDay: Int,   // -1 = no rest day
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    guard let session, session.isPaired, session.isWatchAppInstalled else {
      // Not an error — Watch may not be paired yet. Resolve silently.
      resolve(["sent": false, "reason": "watch_not_available"])
      return
    }

    var context: [String: Any] = [
      "accessToken":  accessToken,
      "refreshToken": refreshToken,
      "expiresAt":    expiresAt,
      "supabaseURL":  supabaseURL,
      "apiBaseURL":   apiBaseURL,
      "dailyGoal":    dailyGoal,
      "reminderHour": reminderHour,
    ]
    if restDay >= 0 { context["restDay"] = restDay }

    do {
      try session.updateApplicationContext(context)
      resolve(["sent": true])
    } catch {
      // Non-fatal — token will be pushed next time auth state changes
      resolve(["sent": false, "reason": error.localizedDescription])
    }
  }

  // Expose connection state so the iOS settings UI can show status
  @objc func getConnectionStatus(
    _ resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    guard let session else {
      resolve(["supported": false])
      return
    }
    resolve([
      "supported":          true,
      "paired":             session.isPaired,
      "watchAppInstalled":  session.isWatchAppInstalled,
      "reachable":          session.isReachable,
    ])
  }

  // ── WCSessionDelegate ──────────────────────────────────────────────────────

  func session(_ session: WCSession, activationDidCompleteWith state: WCSessionActivationState, error: Error?) {
    self.session = session
  }

  func sessionDidBecomeInactive(_ session: WCSession) {}
  func sessionDidDeactivate(_ session: WCSession) {
    WCSession.default.activate()
  }
}
`

const WATCH_MODULE_M = `// WatchConnectivityModule.m
// Auto-generated by plugins/withWatchConnectivity — do not edit manually.
// Exposes WatchConnectivityModule to the React Native bridge.

#import <React/RCTBridgeModule.h>

@interface RCT_EXTERN_MODULE(WatchConnectivity, NSObject)

RCT_EXTERN_METHOD(
  pushTokensToWatch:(NSString *)accessToken
  refreshToken:(NSString *)refreshToken
  expiresAt:(double)expiresAt
  supabaseURL:(NSString *)supabaseURL
  apiBaseURL:(NSString *)apiBaseURL
  dailyGoal:(NSInteger)dailyGoal
  reminderHour:(NSInteger)reminderHour
  restDay:(NSInteger)restDay
  resolve:(RCTPromiseResolveBlock)resolve
  reject:(RCTPromiseRejectBlock)reject
)

RCT_EXTERN_METHOD(
  getConnectionStatus:(RCTPromiseResolveBlock)resolve
  reject:(RCTPromiseRejectBlock)reject
)

@end
`

// ─── Step 1: Write Swift + ObjC bridge files into ios/<AppName>/ ──────────────

function withWatchConnectivityFiles(config) {
  return withDangerousMod(config, [
    'ios',
    async (config) => {
      const appName = config.modRequest.projectName
      const iosDir = path.join(config.modRequest.platformProjectRoot, appName)

      fs.writeFileSync(path.join(iosDir, 'WatchConnectivityModule.swift'), WATCH_MODULE_SWIFT)
      fs.writeFileSync(path.join(iosDir, 'WatchConnectivityModule.m'), WATCH_MODULE_M)

      return config
    },
  ])
}

// ─── Step 2: Add files to Xcode project + link WatchConnectivity.framework ───

function withWatchConnectivityXcode(config) {
  return withXcodeProject(config, (config) => {
    const project = config.modResults
    const appName = config.modRequest.projectName
    const groupName = appName  // the group in Xcode matching the app folder

    // Add Swift file to the main app target if not already present
    const swiftFile = 'WatchConnectivityModule.swift'
    const mFile = 'WatchConnectivityModule.m'

    const existingFiles = project.pbxSourcesBuildPhaseObj(project.getFirstTarget().uuid)
    const alreadyAdded = Object.values(existingFiles?.files ?? {})
      .some((f) => typeof f === 'object' && f.comment?.includes('WatchConnectivityModule'))

    if (!alreadyAdded) {
      // xcode@3 requires a group UUID (not a name) as the third argument to addSourceFile.
      // Find the UUID for the main app group so files land in the right navigator folder.
      const groupUuid = project.findPBXGroupKey({ name: appName }) || undefined
      project.addSourceFile(
        `${appName}/${swiftFile}`,
        { target: project.getFirstTarget().uuid },
        groupUuid
      )
      project.addSourceFile(
        `${appName}/${mFile}`,
        { target: project.getFirstTarget().uuid },
        groupUuid
      )
    }

    // Link WatchConnectivity.framework if not already linked
    const frameworks = project.pbxFrameworksBuildPhaseObj(project.getFirstTarget().uuid)
    const frameworkFiles = Object.values(frameworks?.files ?? {})
    const hasWatchConnectivity = frameworkFiles
      .some((f) => typeof f === 'object' && f.comment?.includes('WatchConnectivity'))

    if (!hasWatchConnectivity) {
      project.addFramework('WatchConnectivity.framework', {
        weak: true,  // weak link — graceful on devices without Watch
        target: project.getFirstTarget().uuid,
      })
    }

    return config
  })
}

// ─── Step 3: Patch AppDelegate.swift — initialise WatchConnectivityModule ────
// The module auto-initialises its WCSession in init(), but React Native only
// instantiates bridge modules lazily. We eagerly create the shared instance
// at app launch so WCSession is active before the JS layer is ready.

function withWatchConnectivityAppDelegate(config) {
  return withDangerousMod(config, [
    'ios',
    async (config) => {
      const appName = config.modRequest.projectName
      const appDelegatePath = path.join(
        config.modRequest.platformProjectRoot,
        appName,
        'AppDelegate.swift'
      )
      if (!fs.existsSync(appDelegatePath)) return config

      let src = fs.readFileSync(appDelegatePath, 'utf8')
      if (src.includes('WatchConnectivity')) return config  // already patched

      // Add WatchConnectivity import
      src = src.replace('import Expo\n', 'import Expo\nimport WatchConnectivity\n')

      // Activate WCSession early in didFinishLaunching, before super call
      src = src.replace(
        '    return super.application(application, didFinishLaunchingWithOptions: launchOptions)',
        '    // Activate WatchConnectivity so tokens can be pushed before JS bridge is ready\n    if WCSession.isSupported() { WCSession.default.activate() }\n\n    return super.application(application, didFinishLaunchingWithOptions: launchOptions)'
      )

      fs.writeFileSync(appDelegatePath, src)
      return config
    },
  ])
}

// ─── Export composed plugin ────────────────────────────────────────────────────

module.exports = function withWatchConnectivity(config) {
  config = withWatchConnectivityFiles(config)
  config = withWatchConnectivityXcode(config)
  config = withWatchConnectivityAppDelegate(config)
  return config
}
